### PR TITLE
Updated examples

### PR DESCRIPTION
**Pull request by bolt12**
I've updated the examples and they work.

### CODE REVIEW

**Comment by audreyt** [comment]
Thanks for your contribution! I'll defer to @ocramz for the release engineering work.

**Comment by ocramz** [comment]
@bolt12 did you pin stack.yaml to a different Stackage version?

**Comment by bolt12** [comment]
I just changed the src/ and examples files!

**Comment by ocramz** [comment]
@bolt12 sorry, I meant to ask what's your exact build configuration for this patch. `stack build` complains because `network-bsd-2.8.1` is not on Stackage, and using the latest Nightly gives module ambiguity problems.

**Comment by bolt12** [comment]
Oh sorry. I use cabal, and the package is on Hackage.. it's weird it isn't available on Stackage.

**Comment by ocramz** [comment]
@audreyt I don't have time to maintain this package anymore, so someone else will have to cut this release.

**Comment by audreyt** [comment]
Ok no problem, I've published https://hackage.haskell.org/package/network-multicast-0.3.0

**Pull request merged**
