### PR TITLE
added stack file

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by ocramz** [comment]
@audreyt Hi, could you make it available on Stackage as well? `stack build` works fine. Thanks!

**Comment by audreyt** [comment]
Hi! Now that I'm digital minister of Taiwan I'd like to offload some of the maint work to capable people. Would you like to upload it to Stackage for me?

**Comment by ocramz** [comment]
Sure; if you wish I can take over its maintenance. I need it for work and I'd rather not see it forgotten.

**Comment by audreyt** [comment]
Awesome, please do so and let me know what I need to do to help.

**Comment by ocramz** [comment]
I have prepared a new version of the package and notified haskell-cafe in
order to be added to the maint list.

Thank you

**Comment by ocramz** [comment]
Hi again,

  sorry to bother you, but it seems you can just add me as a maint with
this link:

http://hackage.haskell.org/package/network-multicast/maintainers/edit

My username is `ocramz` on Hackage as well.

Thank you again and BR,
Marco

**Comment by audreyt** [comment]
Done!

**Pull request merged**
